name: .NET Build and SemVer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool

      - name: Calculate Version
        run: |
          VERSION=$(gitversion /showvariable SemVer)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with versioning
        run: dotnet build -p:Version=$VERSION -p:InformationalVersion=$VERSION

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish artifacts (optional)
        if: success()
        run: dotnet publish -c Release -o output
